@apiURL = http://localhost:5000/api/v1

####
POST {{apiURL}}/auth
Content-Type: application/json

{
  "fname": "oi",
  "lname": "oi",
  "email": "oi@gmail.com",
  "password": "1234"
}


###

POST {{apiURL}}/auth/login
Content-Type: application/json

{
  "email": "oi@gmail.com", 
  "password": "1234"

}

###
GET {{apiURL}}/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9pQGdtYWlsLmNvbSIsImZuYW1lIjoib2kiLCJsbmFtZSI6Im9pIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzU5MjA3MTI1LCJleHAiOjE3NTk4MTE5MjV9.N5RTr1va53T8JT-suVIy2qW3JO64Sbn68SfMBgfAFc4

{

}

###
 GET {{apiURL}}/category
Content-Type: application/json


#####
POST {{apiURL}}/products
Content-Type: application/json

{
  "name": "Nokia Lumia",
  "description": "Ancient Beast",
  "price": 300,
  "stock": 3,
  "category": "68c8f01555ede480a0121d5e",
  "images": ["https://msblogs.thesourcemediaassets.com/2013/08/5543.Lumia925Blk34Combo3ATT_5F00_LR_5F00_1CC4F241.jpg", "https://cdn.mos.cms.futurecdn.net/irLuBqtehijKJiyd8DWum8.jpg"],
  "speacility": "Doesnt break at all"
}


#####
GET {{apiURL}}/products



#####
#### Update product
PATCH {{apiURL}}/products
Content-Type: application/json

{
  "id": "68cfbe279b2684f7f1118e28", 
  "description": "Phone is now discontinued."
}


#####
#### Delete product
DELETE {{apiURL}}/products
Content-Type: application/json

{
  "id": "68cfbe279b2684f7f1118e28"
}
